version: "3.9"

services:
  streamlit_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iitp-seating_attendance
    ports:
      - "8501:8501"
    # Optional but useful if you keep photos on the host
    # and want the app to read them at runtime
    volumes:
      - ./photos:/app/photos
    restart: unless-stopped
